export interface CardPreset {
  id: string;
  name: string;
  shortName: string;
  category: 'CREDIT' | 'EWALLET' | 'DIGITAL' | 'PREPAID' | 'MEMBERSHIP' | 'BANK' | 'DEBIT';
  type: 'CREDIT_CARD' | 'EWALLET' | 'BANK' | 'DEBIT' | 'CASH';
  network: 'VISA' | 'MASTERCARD' | 'OTHER';
  color1: string;
  color2: string;
  defaultCreditLimit?: number;
  badgeText?: string;
  tag?: string;
}

export const CREDIT_CARD_PRESETS: CardPreset[] = [
  // ── BPI ──
  {
    id: 'bpi-rewards',
    name: 'BPI Rewards Card',
    shortName: 'BPI Rewards',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'MASTERCARD',
    color1: '#8B0000',
    color2: '#C8102E',
    defaultCreditLimit: 50000,
    badgeText: 'Rewards',
    tag: 'Points on everyday spend',
  },
  {
    id: 'bpi-gold-rewards',
    name: 'BPI Gold Rewards Card',
    shortName: 'BPI Gold',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'MASTERCARD',
    color1: '#8A6715',
    color2: '#D4AF37',
    defaultCreditLimit: 100000,
    badgeText: 'Gold',
    tag: 'Premium 24K Gold rewards',
  },
  {
    id: 'bpi-platinum-rewards',
    name: 'BPI Platinum Rewards Card',
    shortName: 'BPI Platinum',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'MASTERCARD',
    color1: '#1F2937',
    color2: '#4B5563',
    defaultCreditLimit: 200000,
    badgeText: 'Platinum',
    tag: 'Priority lounge & travel miles',
  },
  {
    id: 'bpi-amore-cashback',
    name: 'BPI Amore Cashback Card',
    shortName: 'BPI Amore',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'VISA',
    color1: '#0B3B24',
    color2: '#C8102E',
    defaultCreditLimit: 75000,
    badgeText: 'Cashback',
    tag: 'Supermarket & dining rebate',
  },
  {
    id: 'bpi-signature',
    name: 'BPI Signature Card',
    shortName: 'BPI Signature',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'VISA',
    color1: '#0A0D14',
    color2: '#1F2430',
    defaultCreditLimit: 500000,
    badgeText: 'Signature',
    tag: 'Ultra-exclusive luxury benefits',
  },

  // ── BDO ──
  {
    id: 'bdo-shopmore-mastercard',
    name: 'BDO ShopMore Mastercard',
    shortName: 'BDO ShopMore',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'MASTERCARD',
    color1: '#003399',
    color2: '#00A3E0',
    defaultCreditLimit: 40000,
    badgeText: 'Shopping',
    tag: 'SM Advantage & mall rewards',
  },
  {
    id: 'bdo-gold-mastercard',
    name: 'BDO Gold Mastercard',
    shortName: 'BDO Gold',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'MASTERCARD',
    color1: '#7B5804',
    color2: '#D4AF37',
    defaultCreditLimit: 100000,
    badgeText: 'Gold',
    tag: 'Double points & travel perk',
  },
  {
    id: 'bdo-visa-classic',
    name: 'BDO Visa Classic',
    shortName: 'BDO Visa',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'VISA',
    color1: '#002B66',
    color2: '#00509E',
    defaultCreditLimit: 30000,
    badgeText: 'Classic',
    tag: 'Everyday lifestyle credit',
  },
  {
    id: 'bdo-platinum-mastercard',
    name: 'BDO Platinum Mastercard',
    shortName: 'BDO Platinum',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'MASTERCARD',
    color1: '#111827',
    color2: '#374151',
    defaultCreditLimit: 300000,
    badgeText: 'Platinum',
    tag: 'Elite concierge & golf privileges',
  },

  // ── METROBANK ──
  {
    id: 'metrobank-titanium-mastercard',
    name: 'Metrobank Titanium Mastercard',
    shortName: 'Metrobank Titanium',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'MASTERCARD',
    color1: '#374151',
    color2: '#6B7280',
    defaultCreditLimit: 60000,
    badgeText: 'Titanium',
    tag: '2x rewards on dining & dept stores',
  },
  {
    id: 'metrobank-platinum-mastercard',
    name: 'Metrobank Platinum Mastercard',
    shortName: 'Metrobank Platinum',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'MASTERCARD',
    color1: '#0F172A',
    color2: '#0284C7',
    defaultCreditLimit: 200000,
    badgeText: 'Platinum',
    tag: 'Premier lifestyle & airport pass',
  },
  {
    id: 'metrobank-m-free-mastercard',
    name: 'Metrobank M Free Mastercard',
    shortName: 'Metrobank M Free',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'MASTERCARD',
    color1: '#0B132B',
    color2: '#38BDF8',
    defaultCreditLimit: 40000,
    badgeText: 'No Annual Fee',
    tag: '0 annual fee forever',
  },
  {
    id: 'metrobank-world-mastercard',
    name: 'Metrobank World Mastercard',
    shortName: 'Metrobank World',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'MASTERCARD',
    color1: '#08080C',
    color2: '#B45309',
    defaultCreditLimit: 500000,
    badgeText: 'World',
    tag: 'Global prestige & luxury travel',
  },

  // ── RCBC ──
  {
    id: 'rcbc-rewards-card',
    name: 'RCBC Rewards Card',
    shortName: 'RCBC Rewards',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'MASTERCARD',
    color1: '#0E3A7E',
    color2: '#2563EB',
    defaultCreditLimit: 50000,
    badgeText: 'Rewards',
    tag: 'Flexible non-expiring rewards',
  },
  {
    id: 'rcbc-visa-platinum',
    name: 'RCBC Visa Platinum',
    shortName: 'RCBC Platinum',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'VISA',
    color1: '#334155',
    color2: '#94A3B8',
    defaultCreditLimit: 150000,
    badgeText: 'Platinum',
    tag: 'Free airport lounge & miles',
  },
  {
    id: 'rcbc-black-card-platinum',
    name: 'RCBC Black Card Platinum',
    shortName: 'RCBC Black Card',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'MASTERCARD',
    color1: '#090A0F',
    color2: '#1E2028',
    defaultCreditLimit: 250000,
    badgeText: 'Black Card',
    tag: 'Stealth luxury & concierge',
  },
  {
    id: 'rcbc-airasia-credit-card',
    name: 'RCBC AirAsia Credit Card',
    shortName: 'RCBC AirAsia',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'VISA',
    color1: '#B91C1C',
    color2: '#EF4444',
    defaultCreditLimit: 60000,
    badgeText: 'AirAsia',
    tag: 'Flight perks & AirAsia points',
  },

  // ── SECURITY BANK ──
  {
    id: 'security-bank-wave-mastercard',
    name: 'Security Bank Wave Mastercard',
    shortName: 'Security Bank Wave',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'MASTERCARD',
    color1: '#064E3B',
    color2: '#10B981',
    defaultCreditLimit: 50000,
    badgeText: 'Wave',
    tag: 'Eco-card with 1% online cashback',
  },
  {
    id: 'security-bank-platinum-mastercard',
    name: 'Security Bank Platinum Mastercard',
    shortName: 'SB Platinum',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'MASTERCARD',
    color1: '#1E293B',
    color2: '#64748B',
    defaultCreditLimit: 200000,
    badgeText: 'Platinum',
    tag: 'Dual currency & dual rewards',
  },
  {
    id: 'security-bank-world-mastercard',
    name: 'Security Bank World Mastercard',
    shortName: 'SB World',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'MASTERCARD',
    color1: '#0B0F19',
    color2: '#D97706',
    defaultCreditLimit: 500000,
    badgeText: 'World',
    tag: 'VIP lounge access & exclusive limits',
  },

  // ── UNIONBANK ──
  {
    id: 'unionbank-rewards-visa',
    name: 'UnionBank Rewards Visa',
    shortName: 'UnionBank Rewards',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'VISA',
    color1: '#C2410C',
    color2: '#F97316',
    defaultCreditLimit: 50000,
    badgeText: 'Rewards',
    tag: '3x points on shopping & dining',
  },
  {
    id: 'unionbank-miles-plus-visa-signature',
    name: 'UnionBank Miles+ Visa Signature',
    shortName: 'UB Miles+ Signature',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'VISA',
    color1: '#0F172A',
    color2: '#1E3A8A',
    defaultCreditLimit: 250000,
    badgeText: 'Miles+ Signature',
    tag: 'Fastest miles earning in PH',
  },
  {
    id: 'unionbank-cash-back-visa',
    name: 'UnionBank Cash Back Visa',
    shortName: 'UB Cash Back',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'VISA',
    color1: '#065F46',
    color2: '#10B981',
    defaultCreditLimit: 60000,
    badgeText: 'Cash Back',
    tag: 'Up to 1.5% unlimited rebate',
  },

  // ── EASTWEST ──
  {
    id: 'eastwest-priority-visa-infinite',
    name: 'EastWest Priority Visa Infinite',
    shortName: 'EW Priority Infinite',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'VISA',
    color1: '#3B0764',
    color2: '#7E22CE',
    defaultCreditLimit: 600000,
    badgeText: 'Priority Infinite',
    tag: 'Luxury purple & unlimited lounge',
  },
  {
    id: 'eastwest-everyday-mastercard',
    name: 'EastWest EveryDay Mastercard',
    shortName: 'EW EveryDay',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'MASTERCARD',
    color1: '#831843',
    color2: '#F43F5E',
    defaultCreditLimit: 50000,
    badgeText: 'EveryDay',
    tag: 'Up to 5% everyday cash rebate',
  },
  {
    id: 'eastwest-platinum-mastercard',
    name: 'EastWest Platinum Mastercard',
    shortName: 'EW Platinum',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'MASTERCARD',
    color1: '#1E293B',
    color2: '#64748B',
    defaultCreditLimit: 200000,
    badgeText: 'Platinum',
    tag: 'Perpetual waiver of annual fees',
  },

  // ── HSBC ──
  {
    id: 'hsbc-red-mastercard',
    name: 'HSBC Red Mastercard',
    shortName: 'HSBC Red',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'MASTERCARD',
    color1: '#7F1D1D',
    color2: '#DC2626',
    defaultCreditLimit: 50000,
    badgeText: 'Red',
    tag: '4x points on online & overseas spend',
  },
  {
    id: 'hsbc-gold-visa-cashback',
    name: 'HSBC Gold Visa Cashback',
    shortName: 'HSBC Gold Cashback',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'VISA',
    color1: '#78350F',
    color2: '#F59E0B',
    defaultCreditLimit: 80000,
    badgeText: 'Gold Cashback',
    tag: '5% rebate on dining & fuel',
  },
  {
    id: 'hsbc-platinum-visa',
    name: 'HSBC Platinum Visa',
    shortName: 'HSBC Platinum',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'VISA',
    color1: '#1F2937',
    color2: '#475569',
    defaultCreditLimit: 200000,
    badgeText: 'Platinum',
    tag: 'Premium travel miles & dining perks',
  },

  // ── PNB ──
  {
    id: 'pnb-ze-lo-mastercard',
    name: 'PNB Ze-Lo Mastercard',
    shortName: 'PNB Ze-Lo',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'MASTERCARD',
    color1: '#064E3B',
    color2: '#059669',
    defaultCreditLimit: 30000,
    badgeText: 'Ze-Lo',
    tag: 'Zero annual fee & zero overlimit fee',
  },
  {
    id: 'pnb-mabuhay-miles-mastercard',
    name: 'PNB Mabuhay Miles Mastercard',
    shortName: 'PNB Mabuhay Miles',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'MASTERCARD',
    color1: '#1E3A8A',
    color2: '#D97706',
    defaultCreditLimit: 100000,
    badgeText: 'Mabuhay Miles',
    tag: 'PAL welcome gift & flight miles',
  },

  // ── MAYA ──
  {
    id: 'maya-black-credit-card',
    name: 'Maya Black Credit Card',
    shortName: 'Maya Black',
    category: 'CREDIT',
    type: 'CREDIT_CARD',
    network: 'VISA',
    color1: '#050505',
    color2: '#10B981',
    defaultCreditLimit: 60000,
    badgeText: 'Black Card',
    tag: 'Next-gen fintech dynamic credit',
  },
];

export const EWALLET_PRESETS: CardPreset[] = [
  {
    id: 'gcash-ewallet',
    name: 'GCash',
    shortName: 'GCash',
    category: 'EWALLET',
    type: 'EWALLET',
    network: 'VISA',
    color1: '#0026B3',
    color2: '#0055FF',
    badgeText: 'E-Wallet',
    tag: 'Top E-Wallet in the Philippines',
  },
  {
    id: 'gcash-visa',
    name: 'GCash Visa Card',
    shortName: 'GCash Visa',
    category: 'EWALLET',
    type: 'EWALLET',
    network: 'VISA',
    color1: '#0026B3',
    color2: '#0055FF',
    badgeText: 'E-Wallet',
    tag: 'Global Visa debit & ATM',
  },
  {
    id: 'gcash-mastercard',
    name: 'GCash Mastercard',
    shortName: 'GCash Mastercard',
    category: 'EWALLET',
    type: 'EWALLET',
    network: 'MASTERCARD',
    color1: '#0033CC',
    color2: '#2563EB',
    badgeText: 'E-Wallet',
    tag: 'Mastercard tap-to-pay',
  },
  {
    id: 'maya-visa-card',
    name: 'Maya Visa Card',
    shortName: 'Maya Visa',
    category: 'EWALLET',
    type: 'EWALLET',
    network: 'VISA',
    color1: '#0B0E14',
    color2: '#00E676',
    badgeText: 'E-Wallet',
    tag: 'Black matte Visa EMV',
  },
  {
    id: 'maya-mastercard',
    name: 'Maya Mastercard',
    shortName: 'Maya Mastercard',
    category: 'EWALLET',
    type: 'EWALLET',
    network: 'MASTERCARD',
    color1: '#2E0854',
    color2: '#D946EF',
    badgeText: 'E-Wallet',
    tag: 'Cyber magenta Mastercard',
  },
  {
    id: 'grabpay-mastercard',
    name: 'GrabPay Mastercard',
    shortName: 'GrabPay',
    category: 'EWALLET',
    type: 'EWALLET',
    network: 'MASTERCARD',
    color1: '#022C22',
    color2: '#059669',
    badgeText: 'E-Wallet',
    tag: 'Grab rides & GrabRewards',
  },
  {
    id: 'shopeepay-virtual-card',
    name: 'ShopeePay Virtual Card',
    shortName: 'ShopeePay',
    category: 'EWALLET',
    type: 'EWALLET',
    network: 'MASTERCARD',
    color1: '#9A3412',
    color2: '#EA580C',
    badgeText: 'E-Wallet',
    tag: 'Shopee cashback & coins',
  },
  {
    id: 'gotyme-visa-debit',
    name: 'GoTyme Bank Visa Debit Card',
    shortName: 'GoTyme Visa',
    category: 'EWALLET',
    type: 'DEBIT',
    network: 'VISA',
    color1: '#0F172A',
    color2: '#00D2C8',
    badgeText: 'Digital Debit',
    tag: 'Go Rewards & free kiosks',
  },
  {
    id: 'wise-prepaid',
    name: 'Wise Prepaid Visa / Mastercard',
    shortName: 'Wise',
    category: 'EWALLET',
    type: 'EWALLET',
    network: 'VISA',
    color1: '#14532D',
    color2: '#84CC16',
    badgeText: 'Multi-Currency',
    tag: 'Low-fee foreign exchange',
  },
  {
    id: 'payoneer-mastercard',
    name: 'Payoneer Prepaid Mastercard',
    shortName: 'Payoneer',
    category: 'EWALLET',
    type: 'EWALLET',
    network: 'MASTERCARD',
    color1: '#1E1B4B',
    color2: '#F97316',
    badgeText: 'Freelance',
    tag: 'International client payouts',
  },
  {
    id: 'paypal-prepaid-mastercard',
    name: 'PayPal Prepaid Mastercard',
    shortName: 'PayPal',
    category: 'EWALLET',
    type: 'EWALLET',
    network: 'MASTERCARD',
    color1: '#003087',
    color2: '#0079C1',
    badgeText: 'E-Wallet',
    tag: 'Direct PayPal wallet link',
  },
  {
    id: 'rcbc-mywallet-visa',
    name: 'RCBC MyWallet Prepaid Visa',
    shortName: 'RCBC MyWallet',
    category: 'EWALLET',
    type: 'EWALLET',
    network: 'VISA',
    color1: '#78350F',
    color2: '#D97706',
    badgeText: 'Prepaid',
    tag: 'Budgeting & cashless reload',
  },
  {
    id: 'bpi-epay-mastercard',
    name: 'BPI ePay Mastercard',
    shortName: 'BPI ePay MC',
    category: 'EWALLET',
    type: 'EWALLET',
    network: 'MASTERCARD',
    color1: '#7F1D1D',
    color2: '#B91C1C',
    badgeText: 'Prepaid',
    tag: 'Secure shopping card',
  },
  {
    id: 'bpi-epay-visa',
    name: 'BPI ePay Visa',
    shortName: 'BPI ePay Visa',
    category: 'EWALLET',
    type: 'EWALLET',
    network: 'VISA',
    color1: '#450A0A',
    color2: '#991B1B',
    badgeText: 'Prepaid',
    tag: 'Safe reloadable visa',
  },
  {
    id: 'banko-debit-card',
    name: 'BanKo Debit Card',
    shortName: 'BanKo Debit',
    category: 'EWALLET',
    type: 'DEBIT',
    network: 'MASTERCARD',
    color1: '#713F12',
    color2: '#EAB308',
    badgeText: 'Microfinance',
    tag: 'BPI Direct BanKo savings',
  },
  {
    id: 'cebuana-24k-card',
    name: 'Cebuana Lhuillier 24k Plus Card',
    shortName: 'Cebuana 24k',
    category: 'EWALLET',
    type: 'EWALLET',
    network: 'OTHER',
    color1: '#78350F',
    color2: '#EAB308',
    badgeText: 'Gold Card',
    tag: 'Remittance loyalty points',
  },
  {
    id: 'palawanpay-card',
    name: 'PalawanPay Card',
    shortName: 'PalawanPay',
    category: 'EWALLET',
    type: 'EWALLET',
    network: 'OTHER',
    color1: '#064E3B',
    color2: '#10B981',
    badgeText: 'E-Wallet',
    tag: 'Suki remittance & payments',
  },
  {
    id: 'beep-card',
    name: 'Beep Card (EMV / Contactless Transit Wallet)',
    shortName: 'Beep Card',
    category: 'EWALLET',
    type: 'EWALLET',
    network: 'OTHER',
    color1: '#1E3A8A',
    color2: '#EAB308',
    badgeText: 'Transit',
    tag: 'LRT, MRT, buses & tollways',
  },
  {
    id: '7eleven-cliqq-card',
    name: '7-Eleven CLiQQ Card',
    shortName: '7-Eleven CLiQQ',
    category: 'EWALLET',
    type: 'EWALLET',
    network: 'OTHER',
    color1: '#18181B',
    color2: '#EA580C',
    badgeText: 'Retail',
    tag: 'Everyday convenience points',
  },
  {
    id: 'paymongo-business-card',
    name: 'PayMongo Business Virtual Mastercard',
    shortName: 'PayMongo',
    category: 'EWALLET',
    type: 'EWALLET',
    network: 'MASTERCARD',
    color1: '#022C22',
    color2: '#10B981',
    badgeText: 'Fintech',
    tag: 'Corporate business expenses',
  },
  {
    id: 'zed-card',
    name: 'ZED Mastercard',
    shortName: 'ZED',
    category: 'EWALLET',
    type: 'CREDIT_CARD',
    network: 'MASTERCARD',
    color1: '#713F12',
    color2: '#EAB308',
    badgeText: 'Credit Card',
    tag: 'Next-Gen 0% foreign fee card',
  },
  {
    id: 'gcash-black',
    name: 'GCash Black Edition Visa',
    shortName: 'GCash Black',
    category: 'EWALLET',
    type: 'EWALLET',
    network: 'VISA',
    color1: '#090A0D',
    color2: '#18181B',
    badgeText: 'Special Edition',
    tag: 'Obsidian carbon with red tech hazard',
  },
  {
    id: 'luvit-card',
    name: 'Luvit E-Wallet Card',
    shortName: 'Luvit',
    category: 'EWALLET',
    type: 'EWALLET',
    network: 'MASTERCARD',
    color1: '#052E16',
    color2: '#166534',
    badgeText: 'E-Wallet',
    tag: 'Smart everyday digital payments',
  },
];

export const DIGITAL_BANK_PRESETS: CardPreset[] = [
  {
    id: 'gotyme-bank',
    name: 'GoTyme Bank Visa Debit Card',
    shortName: 'GoTyme Bank',
    category: 'DIGITAL',
    type: 'BANK',
    network: 'VISA',
    color1: '#0F172A',
    color2: '#00D2C8',
    badgeText: 'Digital Bank',
    tag: 'Earn 3x Go Rewards points',
  },
  {
    id: 'cimb-bank-ph',
    name: 'CIMB Bank Philippines (FastPlus / GSave)',
    shortName: 'CIMB Bank',
    category: 'DIGITAL',
    type: 'BANK',
    network: 'VISA',
    color1: '#7F1D1D',
    color2: '#DC2626',
    badgeText: 'Digital Bank',
    tag: 'High yield savings & Visa debit',
  },
  {
    id: 'maribank-ph',
    name: 'MariBank Philippines',
    shortName: 'MariBank',
    category: 'DIGITAL',
    type: 'BANK',
    network: 'MASTERCARD',
    color1: '#7A0F05',
    color2: '#FA5210',
    badgeText: 'Digital Bank',
    tag: 'Shopee integrated digital bank',
  },
  {
    id: 'salmon-bank',
    name: 'Salmon Digital Bank Card',
    shortName: 'Salmon',
    category: 'DIGITAL',
    type: 'BANK',
    network: 'MASTERCARD',
    color1: '#9F1239',
    color2: '#F43F5E',
    badgeText: 'Digital Bank',
    tag: 'Modern consumer credit & deposits',
  },
  {
    id: 'komo-eastwest',
    name: 'Komo by EastWest Digital Bank',
    shortName: 'Komo',
    category: 'DIGITAL',
    type: 'BANK',
    network: 'VISA',
    color1: '#0E7490',
    color2: '#06B6D4',
    badgeText: 'Digital Bank',
    tag: 'Keep Our Money Online',
  },
  {
    id: 'tonik-digital-bank',
    name: 'Tonik Digital Bank Debit Card',
    shortName: 'Tonik',
    category: 'DIGITAL',
    type: 'BANK',
    network: 'MASTERCARD',
    color1: '#3B0764',
    color2: '#9333EA',
    badgeText: 'Digital Bank',
    tag: 'First digital neobank in PH',
  },
  {
    id: 'ownbank-digital',
    name: 'OwnBank Digital Savings Card',
    shortName: 'OwnBank',
    category: 'DIGITAL',
    type: 'BANK',
    network: 'MASTERCARD',
    color1: '#14532D',
    color2: '#22C55E',
    badgeText: 'Digital Bank',
    tag: 'High interest digital savings',
  },
  {
    id: 'diskartech-rcbc',
    name: 'DiskarTech by RCBC',
    shortName: 'DiskarTech',
    category: 'DIGITAL',
    type: 'BANK',
    network: 'MASTERCARD',
    color1: '#0F766E',
    color2: '#84CC16',
    badgeText: 'Digital Bank',
    tag: 'Taglish digital inclusion app',
  },
  {
    id: 'uno-digital-bank',
    name: 'UNO Digital Bank Card',
    shortName: 'UNO Bank',
    category: 'DIGITAL',
    type: 'BANK',
    network: 'MASTERCARD',
    color1: '#0B0B10',
    color2: '#1E1B4B',
    badgeText: 'Digital Bank',
    tag: 'AI-first unified digital banking',
  },
  {
    id: 'uniondigital-bank',
    name: 'UnionDigital Bank Card',
    shortName: 'UnionDigital',
    category: 'DIGITAL',
    type: 'BANK',
    network: 'VISA',
    color1: '#4C1D95',
    color2: '#7C3AED',
    badgeText: 'Digital Bank',
    tag: 'UnionBank subsidiary digital bank',
  },
  {
    id: 'ofbank-ph',
    name: 'Overseas Filipino Bank (OFBank)',
    shortName: 'OFBank',
    category: 'DIGITAL',
    type: 'BANK',
    network: 'VISA',
    color1: '#002277',
    color2: '#0284C7',
    badgeText: 'Digital Bank',
    tag: 'LandBank digital subsidiary for OFWs',
  },
  {
    id: 'netbank-ph',
    name: 'Netbank Mobile Digital Card',
    shortName: 'Netbank',
    category: 'DIGITAL',
    type: 'BANK',
    network: 'VISA',
    color1: '#18181B',
    color2: '#3F3F46',
    badgeText: 'Digital Bank',
    tag: 'BaaS pioneer digital bank',
  },
];

export const PREPAID_CARD_PRESETS: CardPreset[] = [
  {
    id: 'beep-transit-card',
    name: 'beep™ Contactless Transit Card',
    shortName: 'beep™',
    category: 'PREPAID',
    type: 'EWALLET',
    network: 'OTHER',
    color1: '#1E1B4B',
    color2: '#2563EB',
    badgeText: 'Transit',
    tag: 'LRT, MRT, buses & tollways',
  },
  {
    id: 'starbucks-rewards-card',
    name: 'Starbucks Rewards Card',
    shortName: 'Starbucks',
    category: 'PREPAID',
    type: 'EWALLET',
    network: 'OTHER',
    color1: '#022C22',
    color2: '#059669',
    badgeText: 'Prepaid',
    tag: 'Earn Stars on coffee and bakery',
  },
  {
    id: 'autosweep-rfid-card',
    name: 'Autosweep RFID Toll Card',
    shortName: 'Autosweep RFID',
    category: 'PREPAID',
    type: 'EWALLET',
    network: 'OTHER',
    color1: '#334155',
    color2: '#10B981',
    badgeText: 'RFID Toll',
    tag: 'SLEX, Skyway, NAIAX, MCX, TPLEX',
  },
  {
    id: 'easytrip-rfid-card',
    name: 'Easytrip RFID Toll Card',
    shortName: 'Easytrip RFID',
    category: 'PREPAID',
    type: 'EWALLET',
    network: 'OTHER',
    color1: '#09090B',
    color2: '#0284C7',
    badgeText: 'RFID Toll',
    tag: 'NLEX, SCTEX, CAVITEX, CALAX, C5 Link',
  },
];

export const MEMBERSHIP_CARD_PRESETS: CardPreset[] = [
  {
    id: '7eleven-rewards-card',
    name: '7-Eleven Every Day! Rewards Card',
    shortName: '7-Eleven Rewards',
    category: 'MEMBERSHIP',
    type: 'EWALLET',
    network: 'OTHER',
    color1: '#064E3B',
    color2: '#059669',
    badgeText: 'Loyalty',
    tag: 'Earn points and freebies daily',
  },
  {
    id: 'bistro-group-card',
    name: 'The Bistro Group Privilege Card (BFF Card)',
    shortName: 'The Bistro Group',
    category: 'MEMBERSHIP',
    type: 'EWALLET',
    network: 'OTHER',
    color1: '#0A0A0A',
    color2: '#171717',
    badgeText: 'Dining Club',
    tag: 'TGIFridays, Italianni’s, Texas Roadhouse perks',
  },
  {
    id: 'landers-superstore-card',
    name: 'Landers Superstore Membership Card',
    shortName: 'Landers',
    category: 'MEMBERSHIP',
    type: 'EWALLET',
    network: 'OTHER',
    color1: '#2E1A09',
    color2: '#784D1E',
    badgeText: 'Club Store',
    tag: 'Wholesale superstore & Caltex fuel discounts',
  },
  {
    id: 'mercury-drug-suki',
    name: 'Mercury Drug Suki Card',
    shortName: 'Mercury Drug',
    category: 'MEMBERSHIP',
    type: 'EWALLET',
    network: 'OTHER',
    color1: '#0F172A',
    color2: '#DC2626',
    badgeText: 'Pharmacy',
    tag: 'Nakasisiguro gamot ay bago & Suki points',
  },
  {
    id: 'laking-national-card',
    name: 'Laking National Card (National Book Store)',
    shortName: 'Laking National',
    category: 'MEMBERSHIP',
    type: 'EWALLET',
    network: 'OTHER',
    color1: '#7F1D1D',
    color2: '#DC2626',
    badgeText: 'Books & Crafts',
    tag: 'School supplies, books & stationery points',
  },
  {
    id: 'puregold-perks-card',
    name: 'Puregold Perks / Tindahan ni Aling Puring',
    shortName: 'Puregold Perks',
    category: 'MEMBERSHIP',
    type: 'EWALLET',
    network: 'OTHER',
    color1: '#022C22',
    color2: '#064E3B',
    badgeText: 'Supermarket',
    tag: 'Always panalo grocery cashback points',
  },
  {
    id: 'robinsons-rewards-card',
    name: 'Robinsons Rewards (Go Rewards)',
    shortName: 'Robinsons Rewards',
    category: 'MEMBERSHIP',
    type: 'EWALLET',
    network: 'OTHER',
    color1: '#7F1D1D',
    color2: '#EF4444',
    badgeText: 'Retail Loyalty',
    tag: 'Robinsons, Cebu Pacific, Toys "R" Us',
  },
  {
    id: 'sm-advantage-smac',
    name: 'SM Advantage Card (SMAC)',
    shortName: 'SM SMAC',
    category: 'MEMBERSHIP',
    type: 'EWALLET',
    network: 'OTHER',
    color1: '#1E3A8A',
    color2: '#2563EB',
    badgeText: 'Department Store',
    tag: 'The SM Store, Supermarket, Ace & Watsons',
  },
];

export const PHILIPPINE_BANK_PRESETS: CardPreset[] = [
  // Top Universal & Commercial Banks
  {
    id: 'bdo-unibank',
    name: 'BDO Unibank',
    shortName: 'BDO',
    category: 'BANK',
    type: 'BANK',
    network: 'MASTERCARD',
    color1: '#002B66',
    color2: '#004080',
    badgeText: 'Universal Bank',
    tag: 'We Find Ways',
  },
  {
    id: 'bank-of-the-philippine-islands',
    name: 'Bank of the Philippine Islands (BPI)',
    shortName: 'BPI',
    category: 'BANK',
    type: 'BANK',
    network: 'MASTERCARD',
    color1: '#8B0000',
    color2: '#C8102E',
    badgeText: 'Universal Bank',
    tag: 'Ready Today. Ready Tomorrow.',
  },
  {
    id: 'metrobank',
    name: 'Metropolitan Bank and Trust Company (Metrobank)',
    shortName: 'Metrobank',
    category: 'BANK',
    type: 'BANK',
    network: 'VISA',
    color1: '#002277',
    color2: '#0044CC',
    badgeText: 'Universal Bank',
    tag: 'You’re in Good Hands',
  },
  {
    id: 'landbank',
    name: 'Land Bank of the Philippines (LandBank)',
    shortName: 'LandBank',
    category: 'BANK',
    type: 'BANK',
    network: 'MASTERCARD',
    color1: '#004D25',
    color2: '#0A8A43',
    badgeText: 'Government Bank',
    tag: 'Serving the Nation',
  },
  {
    id: 'pnb',
    name: 'Philippine National Bank (PNB)',
    shortName: 'PNB',
    category: 'BANK',
    type: 'BANK',
    network: 'VISA',
    color1: '#854D0E',
    color2: '#EAB308',
    badgeText: 'Universal Bank',
    tag: 'You Partner Through the Years',
  },
  {
    id: 'security-bank',
    name: 'Security Bank Corporation',
    shortName: 'Security Bank',
    category: 'BANK',
    type: 'BANK',
    network: 'MASTERCARD',
    color1: '#003830',
    color2: '#007366',
    badgeText: 'Universal Bank',
    tag: 'BetterBanking',
  },
  {
    id: 'chinabank',
    name: 'China Banking Corporation (Chinabank)',
    shortName: 'Chinabank',
    category: 'BANK',
    type: 'BANK',
    network: 'MASTERCARD',
    color1: '#7F1D1D',
    color2: '#B91C1C',
    badgeText: 'Universal Bank',
    tag: 'Your Success is Our Business',
  },
  {
    id: 'rcbc',
    name: 'Rizal Commercial Banking Corporation (RCBC)',
    shortName: 'RCBC',
    category: 'BANK',
    type: 'BANK',
    network: 'MASTERCARD',
    color1: '#1E3A8A',
    color2: '#3B82F6',
    badgeText: 'Universal Bank',
    tag: 'Partners Through Generations',
  },
  {
    id: 'unionbank',
    name: 'Union Bank of the Philippines (UnionBank)',
    shortName: 'UnionBank',
    category: 'BANK',
    type: 'BANK',
    network: 'VISA',
    color1: '#C2410C',
    color2: '#EA580C',
    badgeText: 'Universal Bank',
    tag: 'Powering the Future',
  },
  {
    id: 'dbp',
    name: 'Development Bank of the Philippines (DBP)',
    shortName: 'DBP',
    category: 'BANK',
    type: 'BANK',
    network: 'VISA',
    color1: '#002B66',
    color2: '#0284C7',
    badgeText: 'Government Bank',
    tag: 'Building a Strong Republic',
  },
  {
    id: 'eastwest-bank',
    name: 'EastWest Banking Corporation',
    shortName: 'EastWest',
    category: 'BANK',
    type: 'BANK',
    network: 'VISA',
    color1: '#4A044E',
    color2: '#86198F',
    badgeText: 'Universal Bank',
    tag: 'Your Dream Our Focus',
  },
  {
    id: 'aub',
    name: 'Asia United Bank (AUB)',
    shortName: 'AUB',
    category: 'BANK',
    type: 'BANK',
    network: 'MASTERCARD',
    color1: '#1E3A8A',
    color2: '#0284C7',
    badgeText: 'Commercial Bank',
    tag: 'Your Banking Partner',
  },
  {
    id: 'bankcom',
    name: 'Bank of Commerce (BankCom)',
    shortName: 'BankCom',
    category: 'BANK',
    type: 'BANK',
    network: 'MASTERCARD',
    color1: '#7F1D1D',
    color2: '#B91C1C',
    badgeText: 'Universal Bank',
    tag: 'An Affiliate of San Miguel Corp',
  },
  {
    id: 'pbcom',
    name: 'Philippine Bank of Communications (PBCOM)',
    shortName: 'PBCOM',
    category: 'BANK',
    type: 'BANK',
    network: 'VISA',
    color1: '#7F1D1D',
    color2: '#C2410C',
    badgeText: 'Commercial Bank',
    tag: 'Together We Grow',
  },
  {
    id: 'philtrust-bank',
    name: 'Philippine Trust Company (Philtrust Bank)',
    shortName: 'Philtrust',
    category: 'BANK',
    type: 'BANK',
    network: 'OTHER',
    color1: '#1E293B',
    color2: '#475569',
    badgeText: 'Heritage Bank',
    tag: 'Established 1916',
  },
  {
    id: 'veterans-bank',
    name: 'Philippine Veterans Bank',
    shortName: 'Veterans Bank',
    category: 'BANK',
    type: 'BANK',
    network: 'OTHER',
    color1: '#14532D',
    color2: '#166534',
    badgeText: 'Commercial Bank',
    tag: 'A Bank with a Soul',
  },
  {
    id: 'bdo-private-bank',
    name: 'BDO Private Bank',
    shortName: 'BDO Private',
    category: 'BANK',
    type: 'BANK',
    network: 'MASTERCARD',
    color1: '#0B0F19',
    color2: '#1E293B',
    badgeText: 'Wealth Management',
    tag: 'Private Banking',
  },
  {
    id: 'al-amanah-bank',
    name: 'Al-Amanah Islamic Investment Bank of the Philippines',
    shortName: 'Al-Amanah',
    category: 'BANK',
    type: 'BANK',
    network: 'OTHER',
    color1: '#064E3B',
    color2: '#047857',
    badgeText: 'Islamic Bank',
    tag: 'Shari’ah Compliant',
  },

  // Thrift & Savings Banks
  {
    id: 'psbank',
    name: 'Philippine Savings Bank (PSBank)',
    shortName: 'PSBank',
    category: 'BANK',
    type: 'BANK',
    network: 'MASTERCARD',
    color1: '#1E3A8A',
    color2: '#3B82F6',
    badgeText: 'Thrift Bank',
    tag: 'Simple Lang Maaasahan',
  },
  {
    id: 'bpi-direct-banko',
    name: 'BPI Direct BanKo',
    shortName: 'BanKo',
    category: 'BANK',
    type: 'BANK',
    network: 'MASTERCARD',
    color1: '#713F12',
    color2: '#CA8A04',
    badgeText: 'Microfinance',
    tag: 'Kasama sa Pag-asenso',
  },
  {
    id: 'city-savings-bank',
    name: 'City Savings Bank',
    shortName: 'CitySavings',
    category: 'BANK',
    type: 'BANK',
    network: 'VISA',
    color1: '#C2410C',
    color2: '#F97316',
    badgeText: 'Thrift Bank',
    tag: 'Aboitiz Company',
  },
  {
    id: 'sterling-bank-of-asia',
    name: 'Sterling Bank of Asia',
    shortName: 'Sterling Bank',
    category: 'BANK',
    type: 'BANK',
    network: 'VISA',
    color1: '#1E3A8A',
    color2: '#0284C7',
    badgeText: 'Thrift Bank',
    tag: 'An AUB Company',
  },
  {
    id: 'pbb',
    name: 'Philippine Business Bank (PBB)',
    shortName: 'PBB',
    category: 'BANK',
    type: 'BANK',
    network: 'MASTERCARD',
    color1: '#7F1D1D',
    color2: '#DC2626',
    badgeText: 'Thrift Bank',
    tag: 'SME Banking Specialist',
  },
  {
    id: 'bdo-network-bank',
    name: 'BDO Network Bank',
    shortName: 'BDO Network',
    category: 'BANK',
    type: 'BANK',
    network: 'MASTERCARD',
    color1: '#002B66',
    color2: '#0369A1',
    badgeText: 'Rural Bank',
    tag: 'Kabuhayan at Kaagapay',
  },
  {
    id: 'card-bank',
    name: 'CARD Bank',
    shortName: 'CARD Bank',
    category: 'BANK',
    type: 'BANK',
    network: 'OTHER',
    color1: '#15803D',
    color2: '#22C55E',
    badgeText: 'Microfinance',
    tag: 'Mutually Reinforcing Institutions',
  },

  // Digital Banks
  {
    id: 'seabank-philippines',
    name: 'SeaBank Philippines',
    shortName: 'SeaBank',
    category: 'BANK',
    type: 'BANK',
    network: 'MASTERCARD',
    color1: '#C2410C',
    color2: '#FF6B00',
    badgeText: 'Digital Bank',
    tag: 'Daily high interest earnings',
  },
  {
    id: 'maya-bank',
    name: 'Maya Bank',
    shortName: 'Maya Bank',
    category: 'BANK',
    type: 'BANK',
    network: 'MASTERCARD',
    color1: '#090D16',
    color2: '#00E676',
    badgeText: 'Digital Bank',
    tag: 'Digital savings up to 14% p.a.',
  },
  {
    id: 'gotyme-bank-ph',
    name: 'GoTyme Bank',
    shortName: 'GoTyme',
    category: 'BANK',
    type: 'BANK',
    network: 'VISA',
    color1: '#0F172A',
    color2: '#00D2C8',
    badgeText: 'Digital Bank',
    tag: 'Gokongwei Group & Tyme',
  },
  {
    id: 'uniondigital-bank-ph',
    name: 'UnionDigital Bank',
    shortName: 'UnionDigital',
    category: 'BANK',
    type: 'BANK',
    network: 'VISA',
    color1: '#0F172A',
    color2: '#F97316',
    badgeText: 'Digital Bank',
    tag: 'UnionBank subsidiary',
  },
  {
    id: 'tonik-digital-bank-ph',
    name: 'Tonik Digital Bank',
    shortName: 'Tonik',
    category: 'BANK',
    type: 'BANK',
    network: 'MASTERCARD',
    color1: '#3B0764',
    color2: '#9333EA',
    badgeText: 'Digital Bank',
    tag: 'First digital bank in PH',
  },
  {
    id: 'uno-digital-bank-ph',
    name: 'UNO Digital Bank',
    shortName: 'UNO Bank',
    category: 'BANK',
    type: 'BANK',
    network: 'MASTERCARD',
    color1: '#0369A1',
    color2: '#06B6D4',
    badgeText: 'Digital Bank',
    tag: 'Simple, smart digital loans',
  },
  {
    id: 'ofbank',
    name: 'Overseas Filipino Bank (OFBank)',
    shortName: 'OFBank',
    category: 'BANK',
    type: 'BANK',
    network: 'MASTERCARD',
    color1: '#004D25',
    color2: '#10B981',
    badgeText: 'Digital Bank',
    tag: 'Dedicated bank for OFWs',
  },
  {
    id: 'cimb-bank-philippines',
    name: 'CIMB Bank Philippines',
    shortName: 'CIMB Bank',
    category: 'BANK',
    type: 'BANK',
    network: 'VISA',
    color1: '#7F1D1D',
    color2: '#DC2626',
    badgeText: 'Digital Bank',
    tag: 'All-digital pioneer',
  },
  {
    id: 'ownbank',
    name: 'OwnBank',
    shortName: 'OwnBank',
    category: 'BANK',
    type: 'BANK',
    network: 'MASTERCARD',
    color1: '#1E1B4B',
    color2: '#6366F1',
    badgeText: 'Digital Bank',
    tag: 'Flexible daily growth',
  },

  // Foreign Universal & Commercial Banks
  {
    id: 'hsbc-philippines',
    name: 'HSBC Philippines',
    shortName: 'HSBC',
    category: 'BANK',
    type: 'BANK',
    network: 'VISA',
    color1: '#7F1D1D',
    color2: '#B91C1C',
    badgeText: 'Foreign Bank',
    tag: 'Global banking network',
  },
  {
    id: 'citibank-philippines',
    name: 'Citibank Philippines (Corporate Banking)',
    shortName: 'Citibank',
    category: 'BANK',
    type: 'BANK',
    network: 'MASTERCARD',
    color1: '#002B66',
    color2: '#0284C7',
    badgeText: 'Foreign Bank',
    tag: 'Corporate & Institutional Banking',
  },
  {
    id: 'standard-chartered-bank',
    name: 'Standard Chartered Bank Philippines',
    shortName: 'Standard Chartered',
    category: 'BANK',
    type: 'BANK',
    network: 'VISA',
    color1: '#047857',
    color2: '#0284C7',
    badgeText: 'Foreign Bank',
    tag: 'Here for Good',
  },
  {
    id: 'maybank-philippines',
    name: 'Maybank Philippines',
    shortName: 'Maybank',
    category: 'BANK',
    type: 'BANK',
    network: 'VISA',
    color1: '#78350F',
    color2: '#EAB308',
    badgeText: 'Foreign Bank',
    tag: 'Humanising Financial Services',
  },
  {
    id: 'ctbc-bank-philippines',
    name: 'CTBC Bank Philippines',
    shortName: 'CTBC Bank',
    category: 'BANK',
    type: 'BANK',
    network: 'VISA',
    color1: '#064E3B',
    color2: '#0D9488',
    badgeText: 'Foreign Bank',
    tag: 'We are family',
  },
  {
    id: 'deutsche-bank-manila',
    name: 'Deutsche Bank Manila',
    shortName: 'Deutsche Bank',
    category: 'BANK',
    type: 'BANK',
    network: 'OTHER',
    color1: '#0A192F',
    color2: '#0018A8',
    badgeText: 'Foreign Bank',
    tag: 'German Investment Banking',
  },
  {
    id: 'jpmorgan-chase-manila',
    name: 'JPMorgan Chase Bank Manila',
    shortName: 'JPMorgan Chase',
    category: 'BANK',
    type: 'BANK',
    network: 'OTHER',
    color1: '#0B132B',
    color2: '#1C2541',
    badgeText: 'Foreign Bank',
    tag: 'Global Financial Leader',
  },
  {
    id: 'bank-of-america-manila',
    name: 'Bank of America Manila',
    shortName: 'Bank of America',
    category: 'BANK',
    type: 'BANK',
    network: 'OTHER',
    color1: '#7F1D1D',
    color2: '#1E3A8A',
    badgeText: 'Foreign Bank',
    tag: 'Global Corporate Banking',
  },
  {
    id: 'mizuho-bank-manila',
    name: 'Mizuho Bank Manila',
    shortName: 'Mizuho Bank',
    category: 'BANK',
    type: 'BANK',
    network: 'OTHER',
    color1: '#002B66',
    color2: '#1D4ED8',
    badgeText: 'Foreign Bank',
    tag: 'Japanese Mega-Bank',
  },
  {
    id: 'mufg-bank-manila',
    name: 'MUFG Bank Manila',
    shortName: 'MUFG Bank',
    category: 'BANK',
    type: 'BANK',
    network: 'OTHER',
    color1: '#7F1D1D',
    color2: '#991B1B',
    badgeText: 'Foreign Bank',
    tag: 'Mitsubishi UFJ Financial Group',
  },
  {
    id: 'smbc-manila',
    name: 'Sumitomo Mitsui Banking Corporation Manila',
    shortName: 'SMBC',
    category: 'BANK',
    type: 'BANK',
    network: 'OTHER',
    color1: '#14532D',
    color2: '#16A34A',
    badgeText: 'Foreign Bank',
    tag: 'Sumitomo Mitsui Banking',
  },
  {
    id: 'bank-of-china-manila',
    name: 'Bank of China Manila',
    shortName: 'Bank of China',
    category: 'BANK',
    type: 'BANK',
    network: 'OTHER',
    color1: '#7F1D1D',
    color2: '#991B1B',
    badgeText: 'Foreign Bank',
    tag: 'Chinese State Bank',
  },
  {
    id: 'cathay-united-bank-manila',
    name: 'Cathay United Bank Manila',
    shortName: 'Cathay United',
    category: 'BANK',
    type: 'BANK',
    network: 'OTHER',
    color1: '#14532D',
    color2: '#22C55E',
    badgeText: 'Foreign Bank',
    tag: 'Taiwan Mega Financial',
  },
  {
    id: 'icbc-manila',
    name: 'Industrial and Commercial Bank of China (ICBC) Manila',
    shortName: 'ICBC',
    category: 'BANK',
    type: 'BANK',
    network: 'OTHER',
    color1: '#7F1D1D',
    color2: '#B91C1C',
    badgeText: 'Foreign Bank',
    tag: 'World’s Largest Bank by Assets',
  },
  {
    id: 'shinhan-bank-manila',
    name: 'Shinhan Bank Manila',
    shortName: 'Shinhan Bank',
    category: 'BANK',
    type: 'BANK',
    network: 'OTHER',
    color1: '#1E3A8A',
    color2: '#2563EB',
    badgeText: 'Foreign Bank',
    tag: 'Leading Korean Financial Group',
  },
  {
    id: 'keb-hana-bank-manila',
    name: 'KEB Hana Bank Manila',
    shortName: 'KEB Hana',
    category: 'BANK',
    type: 'BANK',
    network: 'OTHER',
    color1: '#064E3B',
    color2: '#0D9488',
    badgeText: 'Foreign Bank',
    tag: 'Korean Global Financial',
  },
  {
    id: 'uob-manila',
    name: 'United Overseas Bank (UOB) Manila',
    shortName: 'UOB',
    category: 'BANK',
    type: 'BANK',
    network: 'OTHER',
    color1: '#1E3A8A',
    color2: '#DC2626',
    badgeText: 'Foreign Bank',
    tag: 'Leading Singaporean Bank',
  },
  {
    id: 'bangkok-bank-manila',
    name: 'Bangkok Bank Manila',
    shortName: 'Bangkok Bank',
    category: 'BANK',
    type: 'BANK',
    network: 'OTHER',
    color1: '#002B66',
    color2: '#EAB308',
    badgeText: 'Foreign Bank',
    tag: 'Thailand’s Leading Bank',
  },
  {
    id: 'anz-manila',
    name: 'Australia and New Zealand Banking Group (ANZ) Manila',
    shortName: 'ANZ Bank',
    category: 'BANK',
    type: 'BANK',
    network: 'OTHER',
    color1: '#002B66',
    color2: '#0284C7',
    badgeText: 'Foreign Bank',
    tag: 'Australia & New Zealand',
  },
  {
    id: 'ing-bank-manila',
    name: 'ING Bank N.V. Manila',
    shortName: 'ING Bank',
    category: 'BANK',
    type: 'BANK',
    network: 'VISA',
    color1: '#C2410C',
    color2: '#EA580C',
    badgeText: 'Foreign Bank',
    tag: 'Dutch Global Banking',
  },
];

export const ALL_CARD_PRESETS: CardPreset[] = [
  ...CREDIT_CARD_PRESETS,
  ...EWALLET_PRESETS,
  ...DIGITAL_BANK_PRESETS,
  ...PREPAID_CARD_PRESETS,
  ...MEMBERSHIP_CARD_PRESETS,
  ...PHILIPPINE_BANK_PRESETS,
];

export type PresetCategory = 'ALL' | 'CREDIT' | 'EWALLET' | 'DIGITAL' | 'PREPAID' | 'MEMBERSHIP' | 'BANK';

export const getPresetsByCategory = (category: PresetCategory): CardPreset[] => {
  if (category === 'ALL') return ALL_CARD_PRESETS;
  if (category === 'CREDIT') return CREDIT_CARD_PRESETS;
  if (category === 'EWALLET') return EWALLET_PRESETS;
  if (category === 'DIGITAL') return DIGITAL_BANK_PRESETS;
  if (category === 'PREPAID') return PREPAID_CARD_PRESETS;
  if (category === 'MEMBERSHIP') return MEMBERSHIP_CARD_PRESETS;
  if (category === 'BANK') return PHILIPPINE_BANK_PRESETS;
  return ALL_CARD_PRESETS;
};

export const searchPresets = (query: string, category: PresetCategory = 'ALL'): CardPreset[] => {
  const base = getPresetsByCategory(category);
  const q = query.trim().toLowerCase();
  if (!q) return base;
  return base.filter(
    p =>
      p.name.toLowerCase().includes(q) ||
      p.shortName.toLowerCase().includes(q) ||
      (p.tag && p.tag.toLowerCase().includes(q)) ||
      (p.badgeText && p.badgeText.toLowerCase().includes(q))
  );
};

export const findPresetByName = (name: string): CardPreset | undefined => {
  const q = (name || '').trim().toLowerCase();
  return ALL_CARD_PRESETS.find(
    p => p.shortName.toLowerCase() === q || p.name.toLowerCase() === q || q.includes(p.shortName.toLowerCase()) || p.shortName.toLowerCase().startsWith(q)
  );
};
